language: node_js
node_js:
- '12'
sudo: false
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_script: bash ./bin/build.sh
script:
- ls -al static/css/style.css
after_success: bash ./bin/deploy.sh
env:
  global:
  - GH_REF: github.com/dwmkerr/hugo_theme_pickles.git
  - secure: PCitxJnDnk0AwJRXFLV4qBxIosIMoehP7MK3CDs0ECLJg/TEagNkQo77786ZUTl9S47UF2vltv81XZdYRgXxcwXGIyrSfnRDr1jqWPno0ihdaIzdz7WHtiK8cf9XtfEo1CnuGuUZ9EEJpvZpBt77nzoBb5uoum8cJHUdFhZ3qC8Xq5hsCz56WqePEzg68KhqlF+Am/iVSQq4FpNd2AY31+uUeIiXyU7azZs8VRUWkrfOKAPOM64xjLk06I5Mf6NloWfRtNcEyoyr74LIlmc4JN8knuKpofU/d0/WTGkscpytCA87xwFZDLeW0Vj8x6S930tshrm0lxsEF+lZCR8LoV6cyPaym7Z/HRM/zZPOY7MCOpiVLTCan/0gcsz1YHvgJZD+5pxkfmnU2c6OxPAGYKmRne+V0KQwqHYYKb5R0EJpHg87Um0TCPtQEuJHA1eHSDO3MIng5SoguXjqQw19IXkHgpb9+JnGKti2YgTGNYosFUWfEYGS7OgRULiJ/nnY2k5uBSCn54nVK58+z5eXjNjmW8oiQXwAYBbJpnHS+3pAU9QC/82IBX2irJJWUKmSbBHTpw/jbYeURKva66kSSMoEMIacaaI5J7wwtMo3trjiWg5sVDz7pEvH3pEczulKOh5XGgT3EcCIgKg9zKxDZ63tCjKlwqP20BxBjGdPuJU=
